version: '3.7'

services:
  # app: 
  #   container_name: app
  #   build: ./app
  #   ports: 
  #     - "${APP_PORT}:${APP_PORT}
  #   depends_on:
  #     - redis_database
  #   environment:
  #     REDIS_HOST: redis_database
  #     REDIS_PORT: "${REDIS_PORT}"
  #   env_file:
  #     - .env

  redis_database:
    container_name: redis_container
    # image: redis:alpine3.16
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    # environment:
    #   REDIS_HOST: ${REDIS_HOST:-"127.0.0.1"}
    #   REDIS_PORT: ${REDIS_PORT:-"6379"}
    #   REDIS_DB: ${REDIS_DB:-"0"}
    env_file:
      - .env